name: Danger.js on Github Actions
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  danger:
    runs-on: ubuntu-latest
    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node: ['12', '14']
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Install yarn
      run: npm install -g yarn
    - name: Install project deps
      run: yarn install --frozen-lockfile
    - name: Run Danger.js script
      run: yarn danger ci https://github.com/w-b-dev/try-dangerjs/pull/3
